[versions]
agp = "8.7.3"
kotlin = "1.9.24"
compileSdk = "34"
minSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

