name: Wear OS CI Workflow

on: [push, workflow_dispatch]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'

      - name: Validate WFF XML
        shell: bash
        run: ./gradlew watchface:validateWffXml

      - name: Build WearOS 4 debug artifacts
        shell: bash
        run: ./gradlew watchface:assembleWear4Debug

      - name: Build WearOS 4 release artifacts
        shell: bash
        run: ./gradlew watchface:assembleWear4Release

      - name: Build WearOS 5 debug artifacts
        shell: bash
        run: ./gradlew watchface:assembleWear5Debug

      - name: Build WearOS 5 release artifacts
        shell: bash
        run: ./gradlew watchface:assembleWear5Release

      - name: Validate memory footprint
        shell: bash
        run: ./gradlew watchface:validateMemoryFootprint

      - uses: actions/upload-artifact@v4
        with:
          path: |
            watchface/build/outputs/apk/wear4/debug/watchface-wear4-debug.apk
            watchface/build/outputs/apk/wear4/release/watchface-wear4-release.apk
            watchface/build/outputs/apk/wear5/debug/watchface-wear5-debug.apk
            watchface/build/outputs/apk/wear5/release/watchface-wear5-release.apk
